import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

const Color mainColor = Colors.black;
const Color primaryClNew = Color(0xFF0C98FF);
const Color whiteColor = CupertinoColors.white;
const Color primaryCl =Color(0xFF8693B7);
const Color borderNewCl =Color.fromRGBO(85, 153, 255, 0.43);
const Color homeBgCl =Color(0xFFF1F9FF);
const Color appBarClNew =Color(0xFFACCDFF);
const Color appBarClNew1 =Color(0xFFD4E6FF);
const Color bgCont =Color(0xFFE9EEFF);
const Color textHeading =Color(0xFF1E1E1E);
const Color screenBgCl = Color(0xFFF1F9FF);
const Color secondaryCl = Color(0xFF112049);
const Color secondary2Cl = Color(0xFF001638);
const Color textGeryCl = Color(0xFF6E6868);
const Color textColorSec = Color(0xFF565656);
const Color blueCl = Color(0xFF0C98FF);
const Color draKText = Color(0xFF001638);
const Color redCl = Color(0xFFED1B1B);
const Color otherCl = Color(0xFFD9D9D9);
const Color greenCl = Color(0xFF037F0F);
const Color kAmber = Color(0xFFf7921e);
const Color textBg = Color(0xFFF1F1F1);
const Color lightGreen = Color(0xffe1f0ea);
const Color lightPink = Color(0xffFFE1E1);
const Color greenSec = Color(0xff00A310);
const Color priceBg = Color(0xffE9EFFF);
const Color lightGreenSec = Color(0xffB7FFAB);
const Color lightRedSec = Color(0xffFFDBC0);
const Color success = Color(0xff29c206);
const Color failure = Color(0xffd20328);
const Color appColor = Color(0xFF152759);
const Color greyNew = Color(0xFFAEAEAE);
const Color trans_white = Color(0xFFFFFF);
const Color pendingCl = Color(0xFFFFA654);
const Color completeCl = Color(0xFF49A53B);
const Color rejectCl = Color(0xFFFF6A6A);
const Color profileTopCl = Color(0xFFA9C9FB);
const Color borderNew = Color(0xFF636E96);

